name: "ci"
on: 
  push:
    branches:
      - master
    paths:
      - "Sources/**"
      - "Tests/**"
  pull_request:
    branches: 
      - '*'

jobs:
  spm:
    name: Test with SPM
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test
